### 获取配置
GET http://localhost:5000/config

### 保存配置
PUT http://localhost:5000/config
Content-Type: application/json

[
  {
    "key": ";&aaaaaa",
    "type:": "remapTo",
    "data": ";"
  },
  {
    "key": ";fd",
    "type:": "runCode",
    "data": "run, shell:downloads"
  }
]
